name: Parameter Demo

on:
  workflow_dispatch:
    inputs:
      USERNAME:
        description: 'Enter username'
        required: true
        default: 'Shalini'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print parameter
        run: echo "Username is ${{ github.event.inputs.USERNAME }}"
